// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shop.Models;

public partial class Activity
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int? Discount { get; set; }

    public DateTime? BeginDate { get; set; }

    public DateTime? EndDate { get; set; }

    public DateTime CreateDate { get; set; }
}