// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shop.Models;

public partial class Cart
{
    public int Id { get; set; }

    public int ProductId { get; set; }

    public int Quantity { get; set; }
}