// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shop.Models;

public partial class Level
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int MemberId { get; set; }

    public virtual Member Member { get; set; }
}