// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shop.Models;

public partial class Member
{
    public int Id { get; set; }

    public string Account { get; set; }

    public string Password { get; set; }

    public string Name { get; set; }

    public int Age { get; set; }

    public virtual ICollection<Cart> Carts { get; set; } = new List<Cart>();

    public virtual ICollection<Level> Levels { get; set; } = new List<Level>();
}