// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Shop.Models;

public partial class User
{
    public int Id { get; set; }

    public string Account { get; set; }

    public string Password { get; set; }

    public DateTime? LoginDatetime { get; set; }

    public DateTime? ModifyDatetime { get; set; }

    public string Role { get; set; }

    public string Nickname { get; set; }
}